TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: false
  DATASET_FEW: HMDB_few_shot
  DATASET: Video_few_shot
  META_BATCH: true  # meta or not
  NUM_CLASSES: 31
  WAY: 5
  SHOT: 5
  SHOT_TEST: 5
  QUERY_PER_CLASS: 5
  QUERY_PER_CLASS_TEST: 1
  NUM_SAMPLES: 1000000
  NUM_TRAIN_TASKS: 10000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 500
  BATCH_SIZE: 1 # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 1
  CLASS_NAME: ['brush hair', 'catch', 'chew', 'clap', 'climb', 'climb stairs', 'dive', 'draw_sword', 'dribble', 'drink', 'fall floor', 'flic flac', 'handstand', 'hug', 'jump', 'kiss', 'pullup', 'punch', 'push', 'ride_bike', 'ride horse', 'shake_hands', 'shoot_bow', 'situp', 'stand', 'sword', 'sword exercise', 'throw', 'turn', 'walk', 'wave']
  NUM_FOLDS: 1
  START_EPOCH: 0
  RANDOM_SEED: 0
  KD_ALPHA: 6.0
  CLS_ALPHA: 1.0
  SIDE_CLS_ALPHA: 1.0
  VIS_ALPHA: 1.0
  KD_T: 10
  LLM_train_json: './prompts/HMDB51_train.json'
  DC_ALPHA: 0.4

TEMP_CLIP: 50.0
TEMP_SIDE: 50.0

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  RANDOM_FLIP: true

LSN:
  EMBED_DIM: 256  
  MLP_RATIO: 4.0
  QKV_BIAS: true
  QK_SCALE: null
  DROP: 0.0
  ATTN_DROP: 0.0
  HIDDEN_DIM: 768
  OUTPUT_DIM: 256
  ADAPTER_DIM: 512
  REDUCE_FACTOR: 3
  GATE_T: 0.1
  GATE_ALPHA: 0
  SIDE_DROPOUT: 0
  USE_GATE: learnable
  REMOVE_PROJ: true
  NUM_LAYERS: 12
  TEMP_LAYERS: [6,8,10]
  LOGITS_T: 4.0
  DROPOUT: 0.6

TEST:
  ENABLE: true
  DATASET: Video_few_shot
  BATCH_SIZE: 1 # Same with NUM_GPUS
  CLASS_NAME: ['fencing', 'kick', 'kick ball', 'pick', 'pour', 'pushup', 'run', 'sit', 'smoke', 'talk']
  USE_TEXT: true
  LOAD_PRETRAIN: true
  PRETRAIN_MODEL_PATH: 'output/hmdb51/5shot/best_checkpoint.pth'
  FUSE_CLIP: 0.55
  FUSE_VISION: 0.4
  FUSE_SIDE: 0.05
  LLM_test_json: './prompts/HMDB51_test.json'

DATA:
  DATA_ROOT_DIR: /ROOT/DATA/
  ANNO_DIR: ./configs/hmdb51/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  TARGET_FPS: 12
  RES_ALPHA: 0.4

LOG_PERIOD: 100
SOLVER:
  GENERATOR_LR: 0.0001
  LSN_LR: 0.0002
  LSNHEAD_LR: 0.0002
  WEIGHT_DECAY: 0.1
  OPTIM_METHOD: adamw
  ADAPTER_ALPHA: 0.5


VIDEO:
  HEAD:
    BACKBONE_NAME: "vit-b-16"
    
  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 1
OUTPUT_DIR: ./output/hmdb51/5shot
OUTPUT_DIR_SAVE: ./output/hmdb51/5shot

