TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: true
  DATASET_FEW: kinetics_few_shot
  DATASET: Video_few_shot
  META_BATCH: true  # meta or not
  NUM_CLASSES: 64
  WAY: 5
  SHOT: 5
  SHOT_TEST: 5
  QUERY_PER_CLASS: 5
  QUERY_PER_CLASS_TEST: 1
  NUM_SAMPLES: 1000000
  NUM_TRAIN_TASKS: 10000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 500
  BATCH_SIZE: 1 # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 1
  CLASS_NAME: ['air drumming', 'arm wrestling', 'beatboxing', 'biking through snow', 'blowing glass', 'blowing out candles', 'bowling', 'breakdancing', 'bungee jumping', 'catching or throwing baseball', 'cheerleading', 'cleaning floor', 'contact juggling', 'cooking chicken', 'country line dancing', 'curling hair', 'deadlifting', 'doing nails', 'dribbling basketball', 'driving tractor', 'drop kicking', 'dying hair', 'eating burger', 'feeding birds', 'giving or receiving award', 'hopscotch', 'jetskiing', 'jumping into pool', 'laughing', 'making snowman', 'massaging back', 'mowing lawn', 'opening bottle', 'playing accordion', 'playing badminton', 'playing basketball', 'playing didgeridoo', 'playing ice hockey', 'playing keyboard', 'playing ukulele', 'playing xylophone', 'presenting weather forecast', 'punching bag', 'pushing cart', 'reading book', 'riding unicycle', 'shaking head', 'sharpening pencil', 'shaving head', 'shot put', 'shuffling cards', 'slacklining', 'sled dog racing', 'snowboarding', 'somersaulting', 'squat', 'surfing crowd', 'trapezing', 'using computer', 'washing dishes', 'washing hands', 'water skiing', 'waxing legs', 'weaving basket']
  NUM_FOLDS: 1
  START_EPOCH: 0
  RANDOM_SEED: 0
  KD_ALPHA: 6.0
  CLS_ALPHA: 0.5
  SIDE_CLS_ALPHA: 1.0
  VIS_ALPHA: 1.0
  KD_T: 10
  LLM_train_json: './prompts/Kinetics_train.json'
  DC_ALPHA: 0.4

TEMP_CLIP: 50.0
TEMP_SIDE: 50.0

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  RANDOM_FLIP: true

LSN:
  EMBED_DIM: 256  
  MLP_RATIO: 4.0
  QKV_BIAS: true
  QK_SCALE: null
  DROP: 0.0
  ATTN_DROP: 0.0
  HIDDEN_DIM: 768
  OUTPUT_DIM: 256
  ADAPTER_DIM: 512
  REDUCE_FACTOR: 3
  GATE_T: 0.1
  GATE_ALPHA: 0
  SIDE_DROPOUT: 0
  USE_GATE: learnable
  REMOVE_PROJ: true
  NUM_LAYERS: 12
  TEMP_LAYERS: [6,8,10]
  LOGITS_T: 4.0
  DROPOUT: 0.7

TEST:
  ENABLE: false
  DATASET: Video_few_shot
  BATCH_SIZE: 1 # Same with NUM_GPUS
  CLASS_NAME: ['blasting sand',  'busking',  'cutting watermelon',  'dancing ballet', 'dancing charleston',  'dancing macarena',  'diving cliff', 'filling eyebrows', 'folding paper',  'hula hooping', 'hurling (sport)',  'ice skating',  'paragliding', 'playing drums',  'playing monopoly', 'playing trumpet', 'pushing car', 'riding elephant',  'shearing sheep', 'side kick', 'stretching arm', 'tap dancing', 'throwing axe',  'unboxing']
  USE_TEXT: true
  FUSE_CLIP: 0.8
  FUSE_VISION: 0.15
  FUSE_SIDE: 0.05
  LLM_test_json: './prompts/Kinetics_test.json'

DATA:
  DATA_ROOT_DIR: /ROOT/DATA/
  ANNO_DIR: ./configs/kinetics100/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  TARGET_FPS: 12
  RES_ALPHA: 0.4

LOG_PERIOD: 100
SOLVER:
  GENERATOR_LR: 0.00005
  LSN_LR: 0.0001
  LSNHEAD_LR: 0.0001
  WEIGHT_DECAY: 0.1
  OPTIM_METHOD: adamw
  ADAPTER_ALPHA: 0.5

VIDEO:
  HEAD:
    BACKBONE_NAME: "vit-b-16"
  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 1
OUTPUT_DIR: ./output/k100/5shot
OUTPUT_DIR_SAVE: ./output/k100/5shot

