TASK_TYPE: classification
TRAIN:
  ENABLE: true
  BATCH_SIZE: 2048
  LOG_FILE: training_log.log
  DATASET: Talfeature
  EVAL_PERIOD: 2
  NUM_FOLDS: 1
  AUTO_RESUME: true
  CHECKPOINT_PERIOD: 10
TEST:
  ENABLE: true
  DATASET: Talfeature
  BATCH_SIZE: 2048
  LOG_FILE: val.log
DATA:
  DATA_ROOT_DIR: 
  ANNO_DIR: 
  NUM_INPUT_FRAMES: 16
  SAMPLING_MODE: interval_based
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [168, 224]
  TRAIN_CROP_SIZE: 112
  TEST_SCALE: 224
  TEST_CROP_SIZE: 112
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  TARGET_FPS: 30
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: false
  COLLATE_FN:
NUM_GPUS: 8
OUTPUT_DIR: 
LOG_PERIOD: 1
LOG_MODEL_INFO: true
LOG_CONFIG_INFO: true
SOLVER:
  MAX_EPOCH: 300
  WEIGHT_DECAY: 1e-3
  OPTIM_METHOD: adam
  NESTEROV: true
AUGMENTATION:
  COLOR_AUG: true
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  IS_SPLIT: false
  USE_GPU: false
  RANDOM_ERASING:
    ENABLE: false
    PROB: 0.25
    MODE: const
    COUNT: [1, 1]
    NUM_SPLITS: 0
    AREA_RANGE: [0.02, 0.33]
    MIN_ASPECT: 0.3
  SSV2_FLIP: false
VIDEO:
  BACKBONE:
    META_ARCH: Identity
  
