TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: false
  DATASET_FEW: Video_few_shot
  DATASET: Video_few_shot
  META_BATCH: true  # meta or not
  NUM_CLASSES: 64
  WAY: 5
  SHOT: 5
  SHOT_TEST: 5
  QUERY_PER_CLASS: 5
  QUERY_PER_CLASS_TEST: 1
  NUM_SAMPLES: 1000000
  NUM_TRAIN_TASKS: 50000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 2000
  BATCH_SIZE: 1 # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 1
  CLASS_NAME: ['Bending [something] until it breaks', 'Closing [something]', 'Covering [something] with [something]', 'Dropping [something] behind [something]', 'Dropping [something] in front of [something]', 'Dropping [something] into [something]', 'Folding [something]', 'Holding [something]', 'Holding [something] next to [something]', 'Letting [something] roll along a flat surface', 'Letting [something] roll down a slanted surface', 'Lifting a surface with [something] on it but not enough for it to slide down', 'Lifting [something] with [something] on it', 'Moving away from [something] with your camera', 'Moving [something] across a surface until it falls down', 'Moving [something] and [something] closer to each other', 'Moving [something] and [something] so they collide with each other', 'Moving [something] down', 'Moving [something] up', 'Plugging [something] into [something]', 'Poking a hole into [something soft]', "Poking [something] so lightly that it doesn't or almost doesn't move", 'Poking [something] so that it falls over', 'Pouring [something] into [something]', 'Pouring [something] into [something] until it overflows', 'Pouring [something] onto [something]', 'Pretending to be tearing [something that is not tearable]', 'Pretending to close [something] without actually closing it', 'Pretending to pick [something] up', 'Pretending to put [something] next to [something]', 'Pretending to spread air onto [something]', 'Pretending to take [something] out of [something]', 'Pulling [something] onto [something]', 'Pulling two ends of [something] so that it gets stretched', 'Pulling two ends of [something] so that it separates into two pieces', 'Pushing [something] from left to right', 'Pushing [something] off of [something]', 'Pushing [something] so that it falls off the table', 'Pushing [something] so that it slightly moves', 'Putting [number of] [something] onto [something]', 'Putting [something] and [something] on the table', "Putting [something] onto a slanted surface but it doesn't glide down", 'Putting [something] onto [something]', 'Putting [something similar to other things that are already on the table]', 'Showing a photo of [something] to the camera', 'Showing [something] behind [something]', '[Something] colliding with [something] and both are being deflected', 'Spilling [something] next to [something]', 'Spilling [something] onto [something]', 'Spinning [something] that quickly stops spinning', 'Spreading [something] onto [something]', 'Squeezing [something]', 'Stuffing [something] into [something]', 'Taking [something] from [somewhere]', 'Tearing [something] into two pieces', "Tilting [something] with [something] on it slightly so it doesn't fall down", 'Tilting [something] with [something] on it until it falls off', 'Tipping [something] with [something in it] over, so [something in it] falls out', 'Turning the camera downwards while filming [something]', 'Turning the camera left while filming [something]', 'Turning the camera upwards while filming [something]', 'Twisting (wringing) [something] wet until water comes out', 'Twisting [something]', 'Uncovering [something]']
  NUM_FOLDS: 1
  START_EPOCH: 0
  RANDOM_SEED: 0
  KD_ALPHA: 0.01
  CLS_ALPHA: 2.0
  SIDE_CLS_ALPHA: 0.1
  VIS_ALPHA: 1.0
  KD_T: 4
  LLM_train_json: './prompts/Ssv2full_train.json'
  DC_ALPHA: 0.4

TEMP_CLIP: 50.0
TEMP_SIDE: 50.0

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true

LSN:
  EMBED_DIM: 256  
  MLP_RATIO: 4.0
  QKV_BIAS: true
  QK_SCALE: null
  DROP: 0.0
  ATTN_DROP: 0.0
  HIDDEN_DIM: 768
  OUTPUT_DIM: 256
  ADAPTER_DIM: 512
  REDUCE_FACTOR: 3
  GATE_T: 0.1
  GATE_ALPHA: 0
  SIDE_DROPOUT: 0
  USE_GATE: learnable
  REMOVE_PROJ: true
  NUM_LAYERS: 12
  TEMP_LAYERS: [6,8,10]
  LOGITS_T: 4.0
  DROPOUT: 0.0

TEST:
  ENABLE: true
  DATASET: Video_few_shot
  BATCH_SIZE: 1 # Same with NUM_GPUS
  CLASS_NAME: ['Approaching [something] with your camera', 'Digging [something] out of [something]', 'Dropping [something] next to [something]', 'Dropping [something] onto [something]', 'Failing to put [something] into [something] because [something] does not fit', 'Lifting up one end of [something] without letting it drop down', 'Picking [something] up', 'Poking a stack of [something] without the stack collapsing', 'Pouring [something] out of [something]', 'Pretending to open [something] without actually opening it', 'Pretending to put [something] behind [something]', 'Pretending to put [something] into [something]', 'Pretending to put [something] underneath [something]', 'Pretending to sprinkle air onto [something]', 'Pulling [something] from left to right', 'Pulling [something] out of [something]', 'Pushing [something] from right to left', 'Removing [something], revealing [something] behind', 'Showing [something] next to [something]', 'Showing that [something] is empty', 'Spilling [something] behind [something]', 'Taking [something] out of [something]', 'Throwing [something] in the air and letting it fall', 'Tipping [something] over']
  USE_TEXT: true
  LOAD_PRETRAIN: true
  PRETRAIN_MODEL_PATH: './output/SSv2_full/5shot/best_checkpoint.pth'
  FUSE_CLIP: 0.05
  FUSE_VISION: 0.7
  FUSE_SIDE: 0.25
  LLM_test_json: './prompts/Ssv2full_test.json'

DATA:
  DATA_ROOT_DIR: /ROOT/DATA/
  ANNO_DIR: ./configs/ssv2_full/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  TARGET_FPS: 12
  RES_ALPHA: 1.6

LOG_PERIOD: 100
SOLVER:
  GENERATOR_LR: 0.0002
  LSN_LR: 0.0002
  LSNHEAD_LR: 0.0002
  WEIGHT_DECAY: 0.1
  OPTIM_METHOD: adamw
  ADAPTER_ALPHA: 1.0

VIDEO:
  HEAD:
    BACKBONE_NAME: "vit-b-16"
  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 1
OUTPUT_DIR: ./output/SSv2_full/5shot
OUTPUT_DIR_SAVE: ./output/SSv2_full/5shot

